sonar.projectKey=cheikhdoss_samapoche
sonar.organization=cheikhdoss
sonar.projectName=SamaPoche
sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/*.g.dart,**/generated/**
sonar.dart.language=on
sonar.coverage.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
