name: CI — Qualité, tests et build
on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  analyse:
    name: Analyse statique (flutter analyze)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter analyze

  tests-unitaires:
    name: Tests unitaires et widgets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter test --coverage
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info

  tests-e2e:
    name: Tests E2E (IHM, navigateur headless)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - uses: nanasess/setup-chromedriver@v2
      - run: flutter pub get
      - name: Lancer chromedriver
        run: chromedriver --port=4444 &
      - name: Exécuter les parcours E2E
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --web-port=8080
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: captures-echec-e2e
          path: screenshots/

  build-web:
    name: Build de production (flutter build web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build web --release
      - uses: actions/upload-artifact@v4
        with:
          name: build-web
          path: build/web

  sonarqube:
    name: Qualimétrie SonarQube
    runs-on: ubuntu-latest
    if: ${{ secrets.SONAR_TOKEN != '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
